# Generated by Django 5.1.1 on 2024-09-22 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_book', '0003_alter_recipe_image_alter_recipe_recipe_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='image',
        ),
    ]
