# Generated by Django 5.1.1 on 2024-09-22 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_book', '0004_remove_recipe_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['recipe_title']},
        ),
    ]
