# Generated by Django 5.1.1 on 2024-09-22 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_book', '0005_alter_recipe_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={},
        ),
    ]
