# Generated by Django 5.1.1 on 2024-09-23 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_book', '0007_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='is_favourite',
            field=models.BooleanField(default=False),
        ),
    ]
